# Generated by Django 4.2.7 on 2023-11-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tari",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nume_tara", models.CharField(max_length=100, unique=True)),
                ("latitudine", models.FloatField()),
                ("longitudine", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Orase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nume_oras", models.CharField(max_length=100)),
                ("latitudine", models.FloatField()),
                ("longitudine", models.FloatField()),
                (
                    "id_tara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.tari"
                    ),
                ),
            ],
            options={
                "unique_together": {("id_tara", "nume_oras")},
            },
        ),
        migrations.CreateModel(
            name="Temperaturi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("valoare", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                (
                    "id_oras",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.orase"
                    ),
                ),
            ],
            options={
                "unique_together": {("id_oras", "timestamp")},
            },
        ),
    ]
